#Project Setup
general:
  productiveBranch: 'master'

#Steps Specific Configuration
steps:
  mavenExecute:
    dockerImage: 'maven:3.5-jdk-7'

  npmExecute:
    dockerImage: 's4sdk/docker-node-browsers'
